var laguList =[['ADA BAND:Kau Auraku:null',
'ADA BAND feat GITA_GUTTAWA:Yang Terbaik Bagimu Ayah:null',
'ADAM SURAJA:Kusuka:null',
'ANGELBERT RAP:Ade Baju Biru:null',
'ADELE:When We Were Young:null',
'ALAN WALKER:Faded:null',
'ALAN WALKER:Rays Of Light:null',
'ALAN WALKER:Sing Me To Sleep:null',
'ALDY MALDINI:Biar Aku Yang Pergi:null',
'ALEXA:Jangan Kau Lepas:null',
'JOHN LEGEND (Cover_By_Jasmine_Thompson):All of Me:null',
'ANAK MENGAJI: Al Quran Surah AT TIN AL ALAQ:null'],
['ANDIEN TYAS:Puisi:null',
'ANJI:Bidadari Tak Bersayap:null',
'ANJI:Bukan Lelaki Sempurna:null',
'ANJI:Dia:null',
'ANJI:Jerawat Rindu:null',
'ARI LASSO:Perbedaan:null',
'ARIANA GRANDE ft._NICKY MINAJ:Side To Side:null',
'ARMADA:Asal Kau Bahagia:null',
'VEVE ZULFIKAR:Assalamu alaika ya Rasulallah:null',
'VIRGOUN:Balasan Surat Cinta Starla:null',
'BATU NISS:Cahaya Bidadari:null',
'BEST of MARSMELLO:Marshmello Original Mix:null'
],
['BLACKOUT:Selalu Ada:null',
           'BRUNO MARS:Just The Way You Are:null',
           'BRUNO MARS:The Lazy Song:null',
           'BRUNO MARS:Versace on The Floor:null',
           'SHEILA ON 7:Buat Aku Tersenyum:null',
           'CASSADRA BAND:Cinta Terbaik:null',
           'CHARLY XCX:Boys:null',
           'VINA PANDUWINATA:Cinta:null',
           'SYMFONY feat ZARA LARSSON:Clean Bandit:null',
           'COLDPLAY:Nature of a Lifetime:null',
           'COVER by FACHRY: Kado Ulang Tahun:null',
           'CRISYE: Seperti Yang Kau Minta:null'
		   ],
['D_MASIV:Natural:null',
            'CLUB EIGHTIES COVER NUFY WARDHANA feat TISSA DINI:Dari Hati:null',
			'DAVID GUETTA ft NICKY MINAJ BEBE REXA AFROJAK:Hey Mama:null',
			'DAVID GUETTA ft. ZARA LARSSON:This Ones For You:null',
			'DAWIN:Dessert:null',
			'DEGA:Memory:null',
			'TEMAN TAPI MENIKAH:Dengarkan Dia(Official_Music_Video):null',
			'LOUIS FONSI ft. DADDY YANKEE (CAROLINA ROSS COVER):Despacito:null',
			'DIDI KEMPOT:Layang Kangen:null',
			'DIDI KEMPOT:Suket Teki:null',
			'DIDI KEMPOT:Stasiun Balapan:null',
			'DJ MORENA:Remix House Musik:null'
			],
['DJ ADE MONIKA:Dj Ade Kaka Jatuh Cinta:null',
            'DJ AKIMILAKU PALING ENAK SEDUNIA:Aisya Maimuna:null',
			'DJ DANCE ASYIK:Despacito:null',
			'DJ SNAKE: Middle:null',
			'DJ TAKBIRAN:Dj Takbiran IdulFitri 2015:null',
			'DJ_NEON:Dj Takbiran:null',
			'DMASIV:Apa Salahku (Official_Video):null',
			'DMASIV:Dengarlah Sayang:null',
			'ECKO SHOW:Gimme Dat:null',
			'ECKO:SHOW:Kid Jaman Now:null',
			'ED_SHEERAN:Perfect:null',
			'ED_SHEERAN:Shape of You:null'
			],
['FIFTH HARMONY ft. TY DOLLA $IGN:Work from Home:null',
            'G-EAZY X BEBE REXHA:Me Myself:null',
			'G-EAZY KEHLANI:Good Life:null',
			'GLENN FRADDLY:Akhir Cerita Cinta:null',
			'GNASH:I Hate U I Love U:null',
			'BANK SINARMA CABANG AMBON:Goyang Tobelo 2017:null',
			'HADDAD ALWI feat FARHAN:Ibu:null',
			'HANIN DHIYA MAUDY AYUNDA:Perahu Kertas:null',
			'HANIN DHIYA:Rindu Setengah Mati:null',
			'HIDUP:Bahagia:null',
			'OPIE LATUL MCP SYSILIA CEVINS:Hioko Tobelo:null',
			'HIP-HOP PAPUA: Naik Turun Oles Trus:null'
			],
['ACOM TALAMBURAN:Hitamkan Pelangi:null',
            'IPANG:Sahabat Kecil:null',
			'JESSIE J ARIANA GRANDE NICKI MINAJ: Ariana Grande Nicki Mina:null',
			'JUDIKA:Bukan Rayuan Gombal:null',
			'REVBLIK:Kasih Dengarkanlah:null',
			'NELLA KHARISMA: Jaran Rocking:null'
			],
['NISSA SABYAN:ALLAHUMMA LABBAIK:null',
            'NISSA SABYAN:DEEN ASSALAM:null',
			'NISSA SABYAN:MAN ANA:null',
			'NISSA SABYAN:Selamat Lebaran:null',
			'NISSA SABYAN:YA ALLAH BIHA:null',
			'NISSA SABYAN:YA ASYIQOL:null','NISSA SABYAN:YA HABIBAL QOLBI:null','Cover By NISSA SABYAN:SAUQBILU YA KHALIQI:null'
			],
['KOMPILASI PEMILU:Jingle Pemilu 1987:null',
'KOMPILASI PEMILU:Jingle pemilu Serentak 2019:null',
'KOMPILASI PEMILU:Lagu Mars Pemilu:null',
'KOMPILASI PEMILU:Lagu Pemilihan Umum:null',
'KOMPILASI PEMILU: Mars Pemilu Orde Baru:null'
],
['COVER KERISPATIH by Abdullah M Irsyad:Tapi Bukan Aku:null',
'COVER ST12 by Abdullah M Irsyad:Cinta Tak Harus Memiliki:null',
'COVER KERISPATIH by Abdullah M Irsyad:Aku Harus Jujur:null']
];