var laguListCari =[[['ADA BAND','Kau','Auraku'],
['ADA BAND feat GITA_GUTTAWA','Yang','Terbaik','Bagimu','Ayah'],
['ADAM SURAJA','Kusuka'],
['ANGELBERT RAP','Ade','Baju','Biru'],
['ADELE','When','We','Were','Young'],
['ALAN WALKER','Faded'],
['ALAN WALKER','Rays','Of','Light'],
['ALAN WALKER','Sing','Me','To','Sleep'],
['ALDY MALDINI','Biar','Aku','Yang','Pergi'],
['ALEXA','Jangan','Kau','Lepas'],
['JOHN LEGEND (Cover_By_Jasmine_Thompson)','All','of','Me'],
['ANAK MENGAJI','Al Quran','Surah AT TIN AL ALAQ']],
[['ANDIEN TYAS','Puisi'],
['ANJI','Bidadari','Tak','Bersayap'],
['ANJI','Bukan','Lelaki','Sempurna'],
['ANJI','Dia'],
['ANJI','Jerawat','Rindu'],
['ARI LASSO','Perbedaan'],
['ARIANA GRANDE ft._NICKY MINAJ','Side','To,'Side'],
['ARMADA','Asal Kau Bahagia'],
['VEVE ZULFIKAR','Assalamu alaika','ya','Rasulallah'],
['VIRGOUN','Balasan','Surat','Cinta','Starla'],
['BATU NISS','Cahaya','Bidadari'],
['BEST of MARSMELLO','Marshmello','Original','Mix']],
[['BLACKOUT','Selalu','Ada'],
           ['BRUNO MARS','Just',The','Way','You','Are'],
           ['BRUNO MARS','The','Lazy','Song'],
           ['BRUNO MARS','Versace','on','The','Floor'],
           ['SHEILA ON 7','Buat','Aku','Tersenyum'],
           ['CASSADRA BAND','Cinta','Terbaik'],
           ['CHARLY XCX','Boys'],
           ['VINA PANDUWINATA','Cinta'],
           ['SYMFONY feat ZARA LARSSON','Clean','Bandit'],
           ['COLDPLAY','Nature','of','a Lifetime'],
           ['COVER by FACHRY','Kado','Ulang','Tahun'],
           ['CRISYE','Seperti','Yang','Kau','Minta']
		   ],
[['D_MASIV','Natural'],
            ['CLUB EIGHTIES COVER NUFY WARDHANA feat TISSA DINI','Dari','Hati'],
			['DAVID GUETTA ft NICKY MINAJ BEBE REXA AFROJAK','Hey','Mama'],
			['DAVID GUETTA ft. ZARA LARSSON','This','Ones','For','You'],
			['DAWIN','Dessert'],
			['DEGA','Memory'],
			['TEMAN TAPI MENIKAH','Dengarkan','Dia(Official_Music_Video)'],
			['LOUIS FONSI ft. DADDY YANKEE (CAROLINA ROSS COVER)','Despacito'],
			['DIDI KEMPOT','Layang','Kangen'],
			['DIDI KEMPOT','Suket','Teki'],
			['DIDI KEMPOT','Stasiun','Balapan'],
			['DJ MORENA','Remix','House','Musik']
			],
[['DJ ADE MONIKA','Dj','Ade','Kaka','Jatuh','Cinta'],
            ['DJ AKIMILAKU PALING ENAK SEDUNIA','Aisya','Maimuna'],
			['DJ DANCE ASYIK','Despacito'],
			['DJ SNAKE','Middle'],
			['DJ TAKBIRAN','Dj','Takbiran','IdulFitri','2015'],
			['DJ_NEON','Dj','Takbiran'],
			['DMASIV','Apa','Salahku','(Official_Video)'],
			['DMASIV','Dengarlah','Sayang'],
			['ECKO SHOW','Gimme','Dat'],
			['ECKO SHOW','Kid','Jaman','Now'],
			['ED_SHEERAN','Perfect'],
			['ED_SHEERAN','Shape','of','You']
			],
[['FIFTH HARMONY ft. TY DOLLA $IGN','Work','from','Home'],
            ['G-EAZY X BEBE REXHA','Me','Myself'],
			['G-EAZY KEHLANI','Good','Life'],
			['GLENN FRADDLY','Akhir','Cerita','Cinta'],
			['GNASH','I Hate','U I Love U'],
			['BANK SINARMA CABANG AMBON','Goyang','Tobelo','2017'],
			['HADDAD ALWI feat FARHAN','Ibu'],
			['HANIN DHIYA MAUDY AYUNDA','Perahu','Kertas'],
			['HANIN DHIYA','Rindu','Setengah','Mati'],
			['HIDUP','Bahagia'],
			['OPIE LATUL MCP SYSILIA CEVINS','Hioko','Tobelo'],
			['HIP-HOP PAPUA','Naik','Turun','Oles','Trus']
			],
[['ACOM TALAMBURAN','Hitamkan','Pelangi'],
            ['IPANG','Sahabat Kecil'],
			['JESSIE J ARIANA GRANDE NICKI MINAJ','Ariana','Grande','Nicki','Mina'],
			['JUDIKA','Bukan','Rayuan','Gombal'],
			['REVBLIK','Kasih','Dengarkanlah'],
			['NELLA KHARISMA','Jaran Rocking']
			],
[['NISSA SABYAN','ALLAHUMMA LABBAIK'],
            ['NISSA SABYAN','DEEN ASSALAM'],
			['NISSA SABYAN','MAN ANA'],
			['NISSA SABYAN','Selamat','Lebaran'],
			['NISSA SABYAN','YA','ALLAH','BIHA'],
			['NISSA SABYAN','YA','ASYIQOL'],['NISSA SABYAN','YA','HABIBAL','QOLBI'],['Cover By NISSA SABYAN','SAUQBILU','YA','KHALIQI']
			],
[['KOMPILASI PEMILU','Jingle','Pemilu','1987'],
['KOMPILASI PEMILU','Jingle','pemilu','Serentak','2019'],
['KOMPILASI PEMILU','Lagu','Mars','Pemilu'],
['KOMPILASI PEMILU','Lagu','Pemilihan','Umum'],
['KOMPILASI PEMILU','Mars','Pemilu','Orde','Baru']
],
[['COVER KERISPATIH by Abdullah M Irsyad','Tapi','Bukan','Aku'],
['COVER ST12 by Abdullah M Irsyad','Cinta','Tak','Harus','Memiliki'],
['COVER KERISPATIH by Abdullah M Irsyad','Aku','Harus','Jujur']]
];