var lagu = ['NISSA SABYAN:ALLAHUMMA LABBAIK:null',
            'NISSA SABYAN:DEEN ASSALAM:null',
			'NISSA SABYAN:MAN ANA:null',
			'NISSA SABYAN:Selamat Lebaran:null',
			'NISSA SABYAN:YA ALLAH BIHA:null',
			'NISSA SABYAN:YA ASYIQOL:null','NISSA SABYAN:YA HABIBAL QOLBI:null','Cover By NISSA SABYAN:SAUQBILU YA KHALIQI:null'
			];