var lagulisting =[['Kau Auraku',
'Yang Terbaik Bagimu Ayah',
'Kusuka',
'Ade Baju Biru',
'When We Were Young',
'Faded',
'Rays Of Light',
'Sing Me To Sleep',
'Biar Aku Yang Pergi',
'Jangan Kau Lepas',
'All of Me',
'Al Quran Surah AT TIN AL ALAQ'],
['Puisi',
'Bidadari Tak Bersayap',
'Bukan Lelaki Sempurna',
'Dia',
'Jerawat Rindu',
'Perbedaan',
'Side To Side',
'Asal Kau Bahagia',
'Assalamu alaika ya Rasulallah',
'Balasan Surat Cinta Starla',
'Cahaya Bidadari',
'Marshmello Original Mix'
],
['Selalu Ada',
           'Just The Way You Are',
           'The Lazy Song',
           'Versace on The Floor',
           'Buat Aku Tersenyum',
           'Cinta Terbaik',
           'Boys',
           'Cinta',
           'Clean Bandit',
           'Nature of a Lifetime',
           'Kado Ulang Tahun',
           'Seperti Yang Kau Minta'
		   ],
['Natural',
            'Dari Hati',
			'Hey Mama',
			'This Ones For You',
			'Dessert',
			'Memory',
			'Dengarkan Dia(Official_Music_Video)',
			'Despacito',
			'Layang Kangen',
			'Suket Teki',
			'Stasiun Balapan',
			'Remix House Musik'
			],
['Dj Ade Kaka Jatuh Cinta',
            'Aisya Maimuna',
			'Despacito',
			'Middle',
			'Dj Takbiran IdulFitri 2015',
			'Dj Takbiran',
			'Apa Salahku',
			'Dengarlah_Sayang',
			'Gimme Dat',
			'Kid Jaman Now',
			'Perfect',
			'Shape of You'
			],
['Work from Home',
            'Me Myself',
			'Good Life',
			'Akhir Cerita Cinta',
			'I Hate U I Love U',
			'Goyang Tobelo 2017',
			'Ibu',
			'Perahu Kertas',
			'Rindu Setengah Mati',
			'Bahagia',
			'Hioko Tobelo',
			'Naik Turun Oles Trus'
			],
['Hitamkan Pelangi',
            'Sahabat Kecil',
			'Ariana Grande Nicki Mina',
			'Bukan Rayuan Gombal',
			'Kasih Dengarkanlah',
			'Jaran Rocking'
			],
['Allahumma Labbaik',
            'Deen Assalam',
			'Man Ana',
			'Selamat Lebaran',
			'Ya Allah Biha',
			'Ya Asyiqal','Ya Habibal Qalbi','Saubiqul Ya Khalqi Cover By Nissa Sabyan'
			],
['Jingle Pemilu 1987',
'Jingle pemilu Serentak 2019',
'Lagu Mars Pemilu',
'Lagu Pemilihan Umum',
'Mars Pemilu Orde Baru'],
['Tapi Bukan Aku',
'Cinta Tak Harus Memiliki','Aku Harus Jujur']
];